namespace FGDDumper
{
    public class EntityDocument
    {
        public string Name { get; init; } = string.Empty;
        public List<EntityPage> Pages { get; init; } = new();

        public string GetMDXText()
        {
            string tabImports = string.Empty;
            string tabs = string.Empty;
            bool isLegacy = false;

            foreach (var page in Pages)
            {
                // i shouldnt have to wonder why this needs .ToUpper() to render the page in the tab, yet here we are!
                tabImports += $"import {page.Game!.FileSystemName.ToUpper()}Page from '@site/src/pages/Entities/{page.GetPageRelativePath()}';\n";
                tabImports += $"import {page.Game.FileSystemName}Icon from '@site/static/img/{page.Game.FileSystemName}_icon.png';\n";

                tabs +=
                $$"""

                <TabItem value="{{page.Game.FileSystemName}}" label={
                    <span>
                        <img src={{{page.Game.FileSystemName}}Icon} alt="{{page.Game.Name}}" className="tab-icon" />
                        {{page.Game.Name}}
                    </span>
                    }>
                    <{{page.Game.FileSystemName.ToUpper()}}Page />
                </TabItem>

                """;

                // treat the document as legacy if any page has the legacy tag
                if (page.Legacy)
                    isLegacy = true;
            }

            var MD =
            $"""   
            ---
            hide_table_of_contents: true
            {(isLegacy ? "sidebar_class_name: legacy_item" : string.Empty)}
            ---

            <!---
            !!!!!!
            THIS PAGE IS AUTOGENERATED FROM GAME FGD DEFINITIONS!
            DO NOT EDIT MANUALLY!
            !!!!!!
            
            In order to make edits, you can make an annotation file in /fgd_dump_overrides
            -->
            
            import Tabs from '@theme/Tabs';
            import TabItem from '@theme/TabItem';
            import '@site/src/css/tabs.css';
            
            # {Name}

            {tabImports}

            <Tabs queryString="game">
                {tabs}
            </Tabs>
            
            """;

            return MD;
        }

        public static EntityDocument GetDocument(string classname, List<EntityPage> pages)
        {
            if (pages.Count == 0)
            {
                throw new InvalidDataException("Cant have an entity document with 0 entity pages!");
            }

            return new EntityDocument
            {
                Name = classname,
                Pages = pages
            };
        }
    }
}
